### PR TITLE
Don't publish to releaseboard

### PR DESCRIPTION
**Pull request by tallenaz**
Related to sul-dlss/operations-tasks#112

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Travis build failed and indicated there is no travis.yml file - add one?

**Review by dazza-codes — CHANGES_REQUESTED** [review]
Get travis build to pass - add a .travis.yml file?

**Comment by tallenaz** [comment]
@darrenleeweber do you know if we have this deployed anywhere? The releaseboard says it was last deployed to archive-catalog-dev(-test) and some sedora machines, none of which I can find any evidence of their existence. I wonder if we are not using the archive-catalog anymore.

**Comment by tallenaz** [comment]
@darrenleeweber a travis build is passing

**Review by dazza-codes — CHANGES_REQUESTED** [review]
The travis build is not running any specs, see
https://travis-ci.org/sul-dlss/archive-catalog/builds/224472387

The travis.ci build should run specs.

**Comment by tallenaz** [comment]
I agree the travis build should run specs. Unfortunately, I'm not able to get tests to run at all on this repository.

**Comment by darrenleeweber** [comment]
Oh no, the specs do not run, and that's not your problem, right.  The bigger question about whether it is deployed has a simple and a complex answer.  The simple answer is 'no'.  The complex answer is that Lynn might want this app to be resurrected at some point.

I'm not sure where that leaves us exactly.  I'd like to get the specs to run, if it's easy.  I may have some time to pair on this in the next week or so.  If that time-frame is too long, let's consider all the options and maybe get a second pair of eyes on it for more options.

What would you like to do with it?

**Comment by tallenaz** [comment]
Since we may want to resurrect this app sometime, and don't need to deploy it now, it doesn't stand in the way of decommissioning the releaseboard. Let me know if you have some time to pair and we can try to get the specs running. FWIW, the tests run, but complain about empty tables. Running the usual rake tasks to get the test db going against sqlite3 don't work, and travis won't install the oracle db adapter, so I believe the problem is somewhere in that vicinity.

**Comment by darrenleeweber** [comment]
Merging this, as is, and will spin off and issue for the backlog on this repo to get the specs running/passing.

**Pull request merged**
